name: Frontend Continuous Integration

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: |
          ls
          cd tourney/
          npm install
        
      - name: Build
        run: |
          ls
          cd tourney/
          npm run build
